name: 'Business Greetings'
description: 'Offers professional greetings and timestamps them'
on:
  push:
    branches:
      - master

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person or team to greet'
        required: true
        default: 'Udacity Learner'
outputs:
  timestamp:
    description: 'Time of greeting'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run greeting script
        run: node index.js