name: Business Greetings
description: Offers professional greetings and timestamps them
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person or team to greet'
        required: true
        default: 'Udacity Learner'
jobs:
  greet:
    runs-on: ubuntu-latest
    outputs:
      timestamp:
        description: 'Time of greeting'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run greeting script
        run: node index.js